### ISSUE TITLE
It is not possible to implement "Normalized" distance.

### ISSUE THREAD

**Issue by generall** [agarie/measurable#14]
In my work I need to use distance function which needs to be initialized with some data. As an example of such distance I can name https://en.wikipedia.org/wiki/Mahalanobis_distance . It needs to be initialized with covariance matrix. Since distances in your lib is just functions, it is impossible to do. Can you suggest any ideas to implement such initialization? Or, if you are interested in, can I offer my assistance with object reimplementation of distance functions?

**Comment by generall** [comment]
My suggestion is: https://github.com/agarie/measurable/pull/15

**Comment by agarie** [comment]
Yep, this is a problem indeed. Let's move this discussion to your PR.
